"""Initial migration

Revision ID: 3d400ce8840e
Revises: efe0a5c26bf6
Create Date: 2024-12-19 23:26:58.078561

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3d400ce8840e'
down_revision = 'efe0a5c26bf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(length=15), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('Families',
    sa.Column('family_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('family_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('primary_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['primary_user_id'], ['Users.user_id'], ),
    sa.PrimaryKeyConstraint('family_id')
    )
    op.create_table('Budgets',
    sa.Column('budget_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('budget_amount', sa.Float(), nullable=False),
    sa.Column('current_amount', sa.Float(), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['Families.family_id'], ),
    sa.PrimaryKeyConstraint('budget_id')
    )
    op.create_table('Expenses',
    sa.Column('expense_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('budget_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['budget_id'], ['Budgets.budget_id'], ),
    sa.PrimaryKeyConstraint('expense_id')
    )
    op.drop_table('families')
    op.drop_table('reports')
    op.drop_table('budgetalerts')
    op.drop_table('userroles')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('email')

    op.drop_table('users')
    op.drop_table('expenses')
    op.drop_table('budgets')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budgets',
    sa.Column('budget_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('family_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('category', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('budget_amount', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('current_amount', mysql.DECIMAL(precision=10, scale=2), server_default=sa.text("'0.00'"), nullable=True),
    sa.Column('is_recurring', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('due_date', sa.DATE(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('amount', mysql.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.family_id'], name='budgets_ibfk_1'),
    sa.PrimaryKeyConstraint('budget_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('expenses',
    sa.Column('expense_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('budget_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('amount', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('category', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('receipt_url', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.budget_id'], name='expenses_ibfk_1'),
    sa.PrimaryKeyConstraint('expense_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('users',
    sa.Column('user_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('password_hash', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('last_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('phone_number', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('email', ['email'], unique=True)

    op.create_table('userroles',
    sa.Column('role_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('family_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('role_name', mysql.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['families.family_id'], name='userroles_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='userroles_ibfk_1'),
    sa.PrimaryKeyConstraint('role_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('budgetalerts',
    sa.Column('alert_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('budget_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('alert_type', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('alert_message', mysql.TEXT(), nullable=True),
    sa.Column('alert_date', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.budget_id'], name='budgetalerts_ibfk_1'),
    sa.PrimaryKeyConstraint('alert_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('reports',
    sa.Column('report_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('family_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('budget_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('report_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('report_date', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('total_budget_amount', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('total_expenses', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('remaining_budget', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('alert_summary', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.budget_id'], name='reports_ibfk_2'),
    sa.ForeignKeyConstraint(['family_id'], ['families.family_id'], name='reports_ibfk_1'),
    sa.PrimaryKeyConstraint('report_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('families',
    sa.Column('family_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('family_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('primary_user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['primary_user_id'], ['users.user_id'], name='families_ibfk_1'),
    sa.PrimaryKeyConstraint('family_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('Expenses')
    op.drop_table('Budgets')
    op.drop_table('Families')
    op.drop_table('Users')
    # ### end Alembic commands ###
